<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [5]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [7]:
%%sql

SELECT
  table_name
FROM
  information_schema.tables
WHERE
  table_schema = 'public'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

6 rows affected.

         table_name
0  currencyexchange
1          customer
2             sales
3              date
4           product
5             store

In [8]:
%%sql

SELECT *
FROM
  sales
LIMIT 110

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

110 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,8003,1,2015-01-08,2015-01-08,1843069,630,1654,4,155.99,134.15,51.68,USD,1.00
106,8004,0,2015-01-08,2015-01-08,498529,270,1694,2,6.22,5.72,2.86,EUR,0.85
107,8004,1,2015-01-08,2015-01-08,498529,270,987,8,320.00,304.00,106.02,EUR,0.85
108,8005,0,2015-01-08,2015-01-08,1754719,540,2157,1,97.42,97.42,49.67,USD,1.00
109,8006,0,2015-01-08,2015-01-08,1426256,660,72,4,35.96,35.96,16.54,USD,1.00

In [9]:
%%sql

SELECT *
FROM currencyexchange
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

         date fromcurrency tocurrency  exchange
0  2015-01-01          AUD        AUD      1.00
1  2015-01-01          AUD        CAD      0.95
2  2015-01-01          AUD        EUR      0.67
3  2015-01-01          AUD        GBP      0.53
4  2015-01-01          AUD        USD      0.82
5  2015-01-01          CAD        AUD      1.05
6  2015-01-01          CAD        CAD      1.00
7  2015-01-01          CAD        EUR      0.71
8  2015-01-01          CAD        GBP      0.55
9  2015-01-01          CAD        USD      0.86

In [10]:
%%sql

SELECT *
FROM store
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,storekey,storecode,geoareakey,countrycode,countryname,state,opendate,closedate,description,squaremeters,status
0,10,1,1,AU,Australia,Australian Capital Territory,2008-01-01,None,Contoso Store Australian Capital Territory,595.00,None
1,20,2,3,AU,Australia,Northern Territory,2008-01-12,2016-07-07,Contoso Store Northern Territory,665.00,Closed
2,30,3,5,AU,Australia,South Australia,2012-01-07,2015-08-08,Contoso Store South Australia,2000.00,Restructured
3,35,3,5,AU,Australia,South Australia,2015-12-08,None,Contoso Store South Australia,3000.00,None
4,40,4,6,AU,Australia,Tasmania,2010-01-01,None,Contoso Store Tasmania,2000.00,None
5,50,5,7,AU,Australia,Victoria,2015-12-09,None,Contoso Store Victoria,2000.00,None
6,60,6,8,AU,Australia,Western Australia,2010-01-01,None,Contoso Store Western Australia,2000.00,None
7,70,7,12,CA,Canada,New Brunswick,2007-05-07,2014-03-09,Contoso Store New Brunswick,1105.00,Restructured
8,72,7,12,CA,Canada,New Brunswick,2015-01-11,2018-02-02,Contoso Store New Brunswick,1500.00,Restructured
9,74,7,12,CA,Canada,New Brunswick,2018-06-02,None,Contoso Store New Brunswick,3500.00,None

In [11]:
%%sql

SELECT *
FROM product
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3
1,2,101002,Contoso 512MB MP3 Player E51 Blue,"Contoso, Ltd",Contoso,Blue,ounces,4.10,6.62,12.99,1,Audio,101,MP4&MP3
2,3,101003,Contoso 1G MP3 Player E100 White,"Contoso, Ltd",Contoso,White,ounces,4.50,7.40,14.52,1,Audio,101,MP4&MP3
3,4,101004,Contoso 2G MP3 Player E200 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.50,11.00,21.57,1,Audio,101,MP4&MP3
4,5,101005,Contoso 2G MP3 Player E200 Red,"Contoso, Ltd",Contoso,Red,ounces,2.40,11.00,21.57,1,Audio,101,MP4&MP3
5,6,101006,Contoso 2G MP3 Player E200 Black,"Contoso, Ltd",Contoso,Black,ounces,8.80,11.00,21.57,1,Audio,101,MP4&MP3
6,7,101007,Contoso 2G MP3 Player E200 Blue,"Contoso, Ltd",Contoso,Blue,ounces,2.10,11.00,21.57,1,Audio,101,MP4&MP3
7,8,101008,Contoso 4G MP3 Player E400 Silver,"Contoso, Ltd",Contoso,Silver,ounces,5.60,30.58,59.99,1,Audio,101,MP4&MP3
8,9,101009,Contoso 4G MP3 Player E400 Black,"Contoso, Ltd",Contoso,Black,ounces,2.10,30.58,59.99,1,Audio,101,MP4&MP3
9,10,101010,Contoso 4G MP3 Player E400 Green,"Contoso, Ltd",Contoso,Green,ounces,11.00,30.58,59.99,1,Audio,101,MP4&MP3

In [13]:
%%sql

SELECT *
FROM customer
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,geoareakey,startdt,enddt,continent,gender,title,givenname,middleinitial,surname,...,zipcode,country,countryfull,birthday,age,occupation,company,vehicle,latitude,longitude
0,15,4,1990-09-10,2034-07-29,Australia,male,Mr.,Julian,A,McGuigan,...,4357,AU,Australia,1965-03-24,55,Border Patrol agent,Cut Rite Lawn Care,2000 Peugeot Kart Up,-27.83,151.17
1,23,8,1995-08-11,2045-01-26,Australia,female,Ms.,Rose,H,Dash,...,6055,AU,Australia,1990-05-10,30,Agricultural and food scientist,Rack N Sack,2005 Volvo XC90,-31.92,116.05
2,36,2,1992-03-12,2044-05-14,Australia,female,Ms.,Annabelle,J,Townsend,...,2304,AU,Australia,1964-07-16,56,Special education teacher,id Boutiques,1999 Lancia Lybra,-32.88,151.71
3,120,6,1983-07-23,2033-08-09,Australia,male,Mr.,Jamie,H,Hetherington,...,7256,AU,Australia,1946-12-11,74,Dental laboratory technician,Showbiz Pizza Place,2006 Dodge Durango,-39.77,144.02
4,180,7,1987-11-26,2026-10-14,Australia,male,Mr.,Gabriel,P,Bosanquet,...,3505,AU,Australia,1955-04-24,65,Administrative support specialist,Dubrow's Cafeteria,1995 Morgan Plus 4,-34.13,142.14
5,185,2,1990-08-01,2029-05-28,Australia,female,Mrs.,Gabrielle,B,Castella,...,2469,AU,Australia,1980-02-23,40,Management dietitian,d.e.m.o.,1997 Alpina B6,-29.01,152.84
6,189,7,2008-07-05,2017-11-01,Australia,female,Ms.,Hayley,C,Jull,...,3377,AU,Australia,1960-04-18,60,Sculptor,Asian Plan,2006 Alpina B5,-37.34,142.91
7,210,2,1980-09-28,2030-05-08,Australia,female,Mrs.,Natalie,L,Hilder,...,2632,AU,Australia,1950-11-23,70,Motel desk clerk,Enrich Garden Services,1995 Ford Fairlane,-36.84,149.05
8,225,7,1985-06-25,2017-09-25,Australia,male,Mr.,Hunter,J,Hutchins,...,3763,AU,Australia,1978-07-20,42,Teletype operator,Mr. Good Buys,2012 Lexus GX,-37.51,145.44
9,243,2,1982-02-07,2027-02-09,Australia,female,Ms.,Maya,J,Atherton,...,2446,AU,Australia,1954-05-15,66,Pilates instructor,Franklin Music,1995 Chevrolet Caprice,-31.36,152.39

In [14]:
%%sql

SELECT *
FROM date
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,date,datekey,year,yearquarter,yearquarternumber,quarter,yearmonth,yearmonthshort,yearmonthnumber,month,monthshort,monthnumber,dayofweek,dayofweekshort,dayofweeknumber,workingday,workingdaynumber
0,2015-01-01,20150101,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Thursday,Thu,5,0,0
1,2015-01-02,20150102,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Friday,Fri,6,1,1
2,2015-01-03,20150103,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Saturday,Sat,7,0,1
3,2015-01-04,20150104,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Sunday,Sun,1,0,1
4,2015-01-05,20150105,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Monday,Mon,2,1,2
5,2015-01-06,20150106,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Tuesday,Tue,3,1,3
6,2015-01-07,20150107,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Wednesday,Wed,4,1,4
7,2015-01-08,20150108,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Thursday,Thu,5,1,5
8,2015-01-09,20150109,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Friday,Fri,6,1,6
9,2015-01-10,20150110,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Saturday,Sat,7,0,6

# Calculate Net Revenue

In [19]:
%%sql

SELECT
  orderdate,
  quantity*netprice*exchangerate AS net_revenue
FROM sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  net_revenue
0  2015-01-01        63.49
1  2015-01-01       423.28
2  2015-01-01       108.75
3  2015-01-01      1146.75
4  2015-01-01       950.25
5  2015-01-01      1302.91
6  2015-01-01        58.73
7  2015-01-01       224.98
8  2015-01-01       263.11
9  2015-01-01       578.52

# Recent Sales >= 2020

In [30]:
%%sql

SELECT
  s.orderdate,
  s.quantity*netprice*exchangerate AS net_revenue,
  c.givenname,
  c.surname,
  c.countryfull,
  c.continent,
  p.productkey,
  p.productname,
  p.categoryname,
  p.subcategoryname
FROM
  sales s
  LEFT JOIN customer c
  ON s.customerkey = c.customerkey
  LEFT JOIN product p
  ON s.productkey = p.productkey
WHERE
   orderdate::date >= '2020-01-01'
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,net_revenue,givenname,surname,countryfull,continent,productkey,productname,categoryname,subcategoryname
0,2020-01-01,99.47,Heike,Burger,Germany,Europe,1810,MGS Bicycle Card Games2009 E166,Games and Toys,Download Games
1,2020-01-01,139.97,Heike,Burger,Germany,Europe,1809,MGS Bicycle Board Games2009 E165,Games and Toys,Download Games
2,2020-01-01,669.39,Heike,Burger,Germany,Europe,698,Proseware Wireless Photo All-in-One Printer M3...,Computers,"Printers, Scanners & Fax"
3,2020-01-01,4090.60,Heike,Burger,Germany,Europe,364,Adventure Works Laptop12 M1200 Black,Computers,Laptops
4,2020-01-01,237.15,Michelle,Seeber,Canada,North America,1288,Contoso Genuine Leather Grip Belt E322 Silver,Cameras and camcorders,Cameras & Camcorders Accessories
5,2020-01-01,1507.16,Jason,Smith,United States,North America,2061,Contoso Microwave 1.5CuFt X0110 Silver,Home Appliances,Microwaves
6,2020-01-01,189.35,Jason,Smith,United States,North America,1717,MGS Flight Simulator X M250,Games and Toys,Download Games
7,2020-01-01,539.90,Jason,Smith,United States,North America,435,Adventure Works Desktop PC1.60 ED160 White,Computers,Desktops
8,2020-01-01,5590.00,James,Frye,United States,North America,451,WWI Desktop PC2.30 M2300 Silver,Computers,Desktops
9,2020-01-01,3580.00,Johnny,Couch,United States,North America,535,WWI LCD19W M100 White,Computers,Monitors

# High VS Low Value ($1000USD)

In [31]:
%%sql

SELECT
  s.orderdate,
  s.quantity*s.netprice*s.exchangerate AS net_revenue,
  c.givenname,
  c.surname,
  c.countryfull,
  c.continent,
  p.productkey,
  p.productname,
  p.categoryname,
  p.subcategoryname,
  CASE
    WHEN s.quantity*s.netprice*s.exchangerate > 1000 THEN 'High Value'
    ELSE 'Low Value'
  END AS High_Low
FROM
  sales s
  LEFT JOIN customer c
  ON s.customerkey = c.customerkey
  LEFT JOIN product p
  ON s.productkey = p.productkey
WHERE
   orderdate::date >= '2020-01-01'
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,net_revenue,givenname,surname,countryfull,continent,productkey,productname,categoryname,subcategoryname,high_low
0,2020-01-01,99.47,Heike,Burger,Germany,Europe,1810,MGS Bicycle Card Games2009 E166,Games and Toys,Download Games,Low Value
1,2020-01-01,139.97,Heike,Burger,Germany,Europe,1809,MGS Bicycle Board Games2009 E165,Games and Toys,Download Games,Low Value
2,2020-01-01,669.39,Heike,Burger,Germany,Europe,698,Proseware Wireless Photo All-in-One Printer M3...,Computers,"Printers, Scanners & Fax",Low Value
3,2020-01-01,4090.60,Heike,Burger,Germany,Europe,364,Adventure Works Laptop12 M1200 Black,Computers,Laptops,High Value
4,2020-01-01,237.15,Michelle,Seeber,Canada,North America,1288,Contoso Genuine Leather Grip Belt E322 Silver,Cameras and camcorders,Cameras & Camcorders Accessories,Low Value
5,2020-01-01,1507.16,Jason,Smith,United States,North America,2061,Contoso Microwave 1.5CuFt X0110 Silver,Home Appliances,Microwaves,High Value
6,2020-01-01,189.35,Jason,Smith,United States,North America,1717,MGS Flight Simulator X M250,Games and Toys,Download Games,Low Value
7,2020-01-01,539.90,Jason,Smith,United States,North America,435,Adventure Works Desktop PC1.60 ED160 White,Computers,Desktops,Low Value
8,2020-01-01,5590.00,James,Frye,United States,North America,451,WWI Desktop PC2.30 M2300 Silver,Computers,Desktops,High Value
9,2020-01-01,3580.00,Johnny,Couch,United States,North America,535,WWI LCD19W M100 White,Computers,Monitors,High Value